app = "brongnal"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sea"

# [mounts]
# source = "catscii_db"
# destination = "/db"

[env]
DB = "TODO"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 8080
    handlers = ["tls"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

