app = "brongnal"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sea"

# [mounts]
# source = "catscii_db"
# destination = "/db"

[env]
DB = "TODO"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 443
    handlers = ["tls"]

  [services.ports.tls_options]
    alpn = ["h2"]

